
ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder
ARG VARIANT="3.10-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT} AS dev_container_auto_added_stage_label

RUN --mount=type=cache,target=/var/cache/apt <<EOF
    apt-get update
    apt-get install -y --no-install-recommends build-essential
EOF




FROM dev_container_feature_content_temp as dev_containers_feature_content_source

FROM $_DEV_CONTAINERS_BASE_IMAGE AS dev_containers_target_stage

USER root

COPY --from=dev_containers_feature_content_source /tmp/build-features/ /tmp/build-features/







ARG _DEV_CONTAINERS_IMAGE_USER=root
USER $_DEV_CONTAINERS_IMAGE_USER

LABEL devcontainer.metadata="[ \
{\"id\":\"ghcr.io/devcontainers/features/common-utils:1\"}, \
{\"id\":\"ghcr.io/devcontainers/features/python:1\",\"customizations\":{\"vscode\":{\"extensions\":[\"ms-python.python\",\"ms-python.vscode-pylance\"],\"settings\":{\"python.defaultInterpreterPath\":\"/usr/local/bin/python\",\"python.formatting.autopep8Path\":\"/usr/local/py-utils/bin/autopep8\",\"python.formatting.blackPath\":\"/usr/local/py-utils/bin/black\",\"python.formatting.yapfPath\":\"/usr/local/py-utils/bin/yapf\",\"python.linting.banditPath\":\"/usr/local/py-utils/bin/bandit\",\"python.linting.flake8Path\":\"/usr/local/py-utils/bin/flake8\",\"python.linting.mypyPath\":\"/usr/local/py-utils/bin/mypy\",\"python.linting.pycodestylePath\":\"/usr/local/py-utils/bin/pycodestyle\",\"python.linting.pydocstylePath\":\"/usr/local/py-utils/bin/pydocstyle\",\"python.linting.pylintPath\":\"/usr/local/py-utils/bin/pylint\"}}}}, \
{\"id\":\"ghcr.io/devcontainers/features/node:1\",\"customizations\":{\"vscode\":{\"extensions\":[\"dbaeumer.vscode-eslint\"]}}}, \
{\"customizations\":{\"vscode\":{\"settings\":{\"python.defaultInterpreterPath\":\"/usr/local/bin/python\",\"python.linting.enabled\":true,\"python.linting.pylintEnabled\":true,\"python.formatting.autopep8Path\":\"/usr/local/py-utils/bin/autopep8\",\"python.formatting.blackPath\":\"/usr/local/py-utils/bin/black\",\"python.formatting.yapfPath\":\"/usr/local/py-utils/bin/yapf\",\"python.linting.banditPath\":\"/usr/local/py-utils/bin/bandit\",\"python.linting.flake8Path\":\"/usr/local/py-utils/bin/flake8\",\"python.linting.mypyPath\":\"/usr/local/py-utils/bin/mypy\",\"python.linting.pycodestylePath\":\"/usr/local/py-utils/bin/pycodestyle\",\"python.linting.pydocstylePath\":\"/usr/local/py-utils/bin/pydocstyle\",\"python.linting.pylintPath\":\"/usr/local/py-utils/bin/pylint\"},\"extensions\":[\"ms-python.python\",\"ms-python.vscode-pylance\"]}},\"remoteUser\":\"vscode\"}, \
{\"customizations\":{\"vscode\":{\"settings\":{\"python.defaultInterpreterPath\":\"/usr/local/bin/python\",\"python.linting.enabled\":true,\"python.linting.pylintEnabled\":true,\"python.formatting.autopep8Path\":\"/usr/local/py-utils/bin/autopep8\",\"python.formatting.blackPath\":\"/usr/local/py-utils/bin/black\",\"python.formatting.yapfPath\":\"/usr/local/py-utils/bin/yapf\",\"python.linting.banditPath\":\"/usr/local/py-utils/bin/bandit\",\"python.linting.flake8Path\":\"/usr/local/py-utils/bin/flake8\",\"python.linting.mypyPath\":\"/usr/local/py-utils/bin/mypy\",\"python.linting.pycodestylePath\":\"/usr/local/py-utils/bin/pycodestyle\",\"python.linting.pydocstylePath\":\"/usr/local/py-utils/bin/pydocstyle\",\"python.linting.pylintPath\":\"/usr/local/py-utils/bin/pylint\",\"python.testing.pytestPath\":\"/usr/local/py-utils/bin/pytest\"},\"extensions\":[\"ms-python.python\",\"ms-python.vscode-pylance\"]}},\"remoteUser\":\"vscode\"} \
]"
